### PR TITLE
Add radio button to address mutually exclusive lemma / case match fields

### LINKED ISSUE #42: Dictionary: Add validation for the flags
The Dictionary panel does not validate the input flags.

The following combination: Match case + Lemma math should be disabled - the user should not be allowed to save a dictionary with this combination, as it is forbidden by the backend.

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #42 - instead of adding validation, this changes the fields from two checkboxes to one field with three options (it updates the values in the JSON to be consistent with the checkboxes though).

Updated field:
image

### CODE REVIEW

**Comment by laurachiticariu** [comment]
@marthacryan looks good but one request: The 3 options as listed now are a bit too verbose. Can we list the options in this order with this text:
1. Ignore case
2. Case insensitive
3. Lemma match

We can explain in docs that Lemma match ignores case.

**Comment by laurachiticariu** [comment]
@marthacryan also a question: if the UI changes, I assume flows saved with the prior organization of the UI will not load correctly? Or will they?

**Comment by marthacryan** [comment]
> @marthacryan looks good but one request: The 3 options as listed now are a bit too verbose. Can we list the options in this order with this text:
> 
> 1. Ignore case
> 2. Case insensitive
> 3. Lemma match
> 
> We can explain in docs that Lemma match ignores case.

Ok - sorry just to make sure, did you mean for #2 to be case sensitive? Not sure the difference between case insensitive and ignore case

**Comment by marthacryan** [comment]
> also a question: if the UI changes, I assume flows saved with the prior organization of the UI will not load correctly? Or will they?

I coded it so that it'd match the JSON so it should be compatible both ways (older flows will still work and current flows should work on the older UI)

**Comment by laurachiticariu** [comment]
Yes, 2 should be case sensitive, I fixed now.

**Comment by laurachiticariu** [comment]
@marthacryan let's use `Match case` instead of `Case sensitive` - it's simpler to understand

**Comment by marthacryan** [comment]
@laurachiticariu Updated that wording / order

**Review by laurachiticariu — APPROVED** [review]
👍

**Pull request merged**
